name: infinity-arcade
adopt-info: infinity-arcade-backend
base: core24
summary: AI-powered game generator and arcade using Lemonade Server
description: |
  Infinity Arcade is an AI-powered game generator that combines a ChatGPT-like
  interface with a game runtime to generate and play retro-style games using
  large language models via Lemonade Server.

  Features:
  - Generate unique games by describing what you want to play
  - Play classic-style arcade games rendered with Pygame
  - Built-in demo games to get started
  - Powered by AMD's Lemonade Server for local AI inference

grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

license: MIT
website: https://github.com/lemonade-sdk/infinity-arcade
source-code: https://github.com/lemonade-sdk/infinity-arcade
issues: https://github.com/kenvandine/infinity-arcade-snap/issues
contact: https://github.com/kenvandine/infinity-arcade-snap/issues

plugs:
  foo-install-lemonade:
    interface: content
    content: foo
    target: $SNAP_DATA/foo
    default-provider: lemonade-server

apps:
  infinity-arcade:
    command: bin/infinity-arcade-launcher
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - audio-playback
      - browser-support
    environment:
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages
      SDL_VIDEODRIVER: x11
      SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR: 0
      PYGAME_HIDE_SUPPORT_PROMPT: 1
      ELECTRON_DISABLE_SANDBOX: 1
      ELECTRON_OZONE_PLATFORM_HINT: auto
      PATH: $SNAP/bin:$PATH

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

parts:
  launcher:
    plugin: dump
    source: scripts/
    organize:
      infinity-arcade-launcher: bin/infinity-arcade-launcher
      lemonade-server: bin/lemonade-server
    stage-packages:
      - curl

  electron-app:
    plugin: dump
    source: electron-app/
    build-packages:
      - npm
      - git
    override-build: |
      npm install
      npm run build
      # Create the destination directory
      mkdir -p $CRAFT_PART_INSTALL/web-app
      mv dist/linux*-unpacked/* $CRAFT_PART_INSTALL/web-app/
    prime:
      - web-app
      - -*/chrome-sandbox
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  infinity-arcade-backend:
    plugin: python
    source: https://github.com/lemonade-sdk/infinity-arcade.git
    source-tag: v0.3.0
    python-packages:
      - pip
      - wheel
      - setuptools
    build-packages:
      - python3-dev
      - python3-pip
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - python3-minimal
      - libpython3.12
    override-pull: |
      craftctl default
      VERSION=$(craftctl get version)
      if [ -z $VERSION ]; then
        VERSION=$(git describe --tags --abbrev=10)
        craftctl set version=$VERSION
      fi
    override-build: |
      craftctl default
      # Install the infinity-arcade package
      pip install . --target $CRAFT_PART_INSTALL/lib/python3.12/site-packages --no-deps
      # Install Python dependencies
      pip install fastapi uvicorn pygame httpx jinja2 python-multipart openai \
        --target $CRAFT_PART_INSTALL/lib/python3.12/site-packages

  cleanup:
    after: [ infinity-arcade-backend, electron-app ]
    plugin: nil
    build-snaps: [ gnome-46-2404 ]
    override-prime: |
        set -eux
        cd /snap/gnome-46-2404/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
